### ISSUE TITLE
Lowish: Screen Pops Up Whenever Editing a Post/Page, Then Disappears

### ISSUE THREAD

**Issue by davidshq** [jtsternberg/GC-Sermons#10]
When I go in to add/edit a page/post, when it loads initially for editing and when it comes back around after I've clicked on update/publish it pops up again. It is literally just a second - so fast I can't see what it is exactly.

If I disable GC-Sermons it goes away, if I enable the plugin again, it comes back.

It isn't something which causes work stoppages.

**Comment by jtsternberg** [comment]
Interesting.. Looking at the code, there doesn't look to be anything that would cause that. I'm not doubting you, but I'm not able to replicate. Any more info you can provide would be helpful. thank you.

**Comment by jtsternberg** [comment]
With latest version, this should be resolved. It was occurring when the modal css was loaded after the modal markup.
