### ISSUE TITLE
FitVids Not Working?

### ISSUE THREAD

**Issue by davidshq** [jtsternberg/GC-Sermons#12]
When I initially installed GC Sermons I saw that the message videos weren't acting responsively. I didn't notice that FitVids should have taken care of this, so I added my own code to handle it...

But later I noticed that FitVids was included with the GC Sermons manager...so I'm unsure why the message video wasn't acting responsive.

I removed my code and tested once again, but still it wasn't responsive. Unsure what is causing this. The video I am embedding is from Vimeo.

**Comment by jtsternberg** [comment]
FitVids is only enqueued/used when the sermon_play_button shortcode is used. But you can enqueue it for your own purposes, as demonstrated in this gist: https://gist.github.com/jtsternberg/8e24f827efa9c6cb9ed8000dd1e9772e#file-content-sermon-php-L25-L38
