### ISSUE TITLE
Add Shortcode for Recent Sermons

### ISSUE THREAD

**Issue by davidshq** [jtsternberg/GC-Sermons#16]
It would be nice to have a shortcode like [recent_series] that would output the x most recent sermons, regardless of series.

This is a low priority item for me personally.

**Comment by jtsternberg** [comment]
That's what the GC Sermons (`[gc_sermons]`) shortcode is for.

```
[gc_sermons per_page="8"  content="" thumbnail_size="medium" number_columns="4" wrap_classes="xtra-wrap"]
```

looks like:
![](http://b.ustin.co/181jR+)

button:
![](http://b.ustin.co/10gNJ+)

modal:
![](http://b.ustin.co/1HFVeT+)

**Comment by davidshq** [comment]
Got it. At first I didn't think this would work, as I wanted to show only the first four sermons and didn't want pagination, but now I've tested it with the no pagination option and it works perfectly.
