### ISSUE TITLE
[Ultra Low Priority]

### ISSUE THREAD

**Issue by davidshq** [jtsternberg/GC-Sermons#8]
When installing the GC-Sermons plugin for the first time when the Plugins page loads after the install there are two messages:
"This plugin requires the following plugins: CMB2 and WDS Shortcodes
Begin Installing plugins | Dismiss this notice"

And
"GC Sermons is missing requirements and has been deactivated. Please make sure all requirements are available. Requirements: CMB2"

Entirely unnecessary, but for end user experience might be nice to show one message instead of both.

**Comment by jtsternberg** [comment]
Yah, that's a bug. Also, wds-shortcodes is bundled now, so shouldn't be listed as a requirement.

**Comment by jtsternberg** [comment]
I just pushed a fix. Can you test?

**Comment by jtsternberg** [comment]
Like #9, this should be fixed.
