### ISSUE TITLE
Lowish: Installing Required Plugins Results in Permissions Error

### ISSUE THREAD

**Issue by davidshq** [jtsternberg/GC-Sermons#9]
This could be a show-stopper for non-technical users.

If one goes to install the required plugins, the plugin is installed but it then tries to return you to:

wp-admin/plugins.php?page=install-required-plugins

At which time you are presented with the error message:

"You do not have sufficient permissions to access this page."

Reloading the page displays the same error.

One can successfully go back to the dashboard: /wp-admin/

But it appears all messages have been dismissed, even though (in this case) I installed only one of the two required plugins.

In fact, one can no longer find the required plugins navigation, it has disappeared.

**Comment by jtsternberg** [comment]
Good catch, I'll check that out. Thanks.

**Comment by jtsternberg** [comment]
I just pushed a fix. Can you test?

**Comment by jtsternberg** [comment]
This should also be fixed with latest version. If not, please reopen.
